# Custom exceptions belong in this module.

class FooError(Exception):
	pass
